# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OpgW_CEfg04QhZKbNRstGh75qaJuEpFJ
"""

# Importing necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load the dataset directly from URL
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/airline-passengers.csv"
df = pd.read_csv(url, usecols=['Month', 'Passengers'])

# Display the first few rows of the dataset
print("Step 1: Loading time series dataset correctly in Pandas\n")
print(df.head())

# Step 2: Indexing in Time-Series Data
# Convert the 'Month' column to datetime format and set it as index
df['Month'] = pd.to_datetime(df['Month'])
df.set_index('Month', inplace=True)

# Display the first few rows of the modified dataset
print("\nStep 2: Indexing in Time-Series Data\n")
print(df.head())

# Step 3: Time-Resampling using Pandas
# Resample the data to get the sum of passengers for each year
resampled_df = df.resample('Y').sum()

# Display the resampled data
print("\nStep 3: Time-Resampling using Pandas\n")
print(resampled_df.head())

# Step 4: Rolling Time Series
# Calculate the rolling mean of passengers over a window of 12 months
rolling_mean = df.rolling(window=12).mean()

# Display the rolling mean
print("\nStep 4: Rolling Time Series\n")
print(rolling_mean.head(20))

# Step 5: Plotting Time-series Data using Pandas
# Plot the original time series data and rolling mean
plt.figure(figsize=(10, 6))
plt.plot(df.index, df['Passengers'], label='Original Data')
plt.plot(rolling_mean.index, rolling_mean['Passengers'], label='Rolling Mean', color='red')
plt.title('Passenger Counts Over Time')
plt.xlabel('Date')
plt.ylabel('Passenger Count')
plt.legend()
plt.show()